In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') # ignore warnings message

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)


## EPL

In [3]:
train=pd.read_csv("datasets/epl_data_train_onehot.csv")
test=pd.read_csv("datasets/epl_data_test_onehot.csv")
# print(train.head())
# print(train.shape)

X_train = train.drop(columns = ['FTR'])
y_train = train['FTR']
print(X_train.shape)
print(y_train.shape)

X_test = test.drop(columns = ['FTR'])
y_test = test['FTR']
print(X_test.shape)
print(y_test.shape)

(2660, 29)
(2660,)
(380, 29)
(380,)


## Predict

### Decision Tree

In [6]:
from sklearn.tree import DecisionTreeClassifier as DT
from sklearn import metrics

modelDT = DT()
modelDT = modelDT.fit(X_train, y_train)
preds_DT = modelDT.predict(X_test)

print('Accuracy of DecisionTreeClassifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, preds_DT)))
print('Logistic Regression Confusion Matrix \n', metrics.confusion_matrix(y_test, preds_DT))

Accuracy of DecisionTreeClassifier on test set: 0.39
Logistic Regression Confusion Matrix 
 [[40 28 42]
 [24 27 46]
 [42 50 81]]


### Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn import metrics

model_LR = LR(random_state=0)
model_LR = model_LR.fit(X_train, y_train)
pred_LR = model_LR.predict(X_test)

print('Accuracy of Logistic Regression classifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, pred_LR)))
print('Logistic Regression Confusion Matrix \n', metrics.confusion_matrix(y_test, pred_LR))

Accuracy of Logistic Regression classifier on test set: 0.53
Logistic Regression Confusion Matrix 
 [[ 52  13  45]
 [ 17   8  72]
 [ 25   8 140]]


### XGB Classifier

In [8]:
from xgboost import XGBClassifier

model_XGB = XGBClassifier()
model_XGB.fit(X_train, y_train)
pred_XGB = model_XGB.predict(X_test)

print('Accuracy of XGBoost classifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, pred_XGB)))
print('XGBoost - Confusion Matrix \n', metrics.confusion_matrix(y_test, pred_XGB))

Accuracy of XGBoost classifier on test set: 0.50
XGBoost - Confusion Matrix 
 [[ 42  25  43]
 [ 20  21  56]
 [ 20  27 126]]


## La Liga

In [11]:
train=pd.read_csv("datasets/laliga_data_train_onehot.csv")
test=pd.read_csv("datasets/laliga_data_test_onehot.csv")
# print(train.head())
# print(train.shape)

X_train = train.drop(columns = ['FTR'])
y_train = train['FTR']
print(X_train.shape)
print(y_train.shape)

X_test = test.drop(columns = ['FTR'])
y_test = test['FTR']
print(X_test.shape)
print(y_test.shape)

(2660, 29)
(2660,)
(380, 29)
(380,)


### Decision Tree

In [12]:
from sklearn.tree import DecisionTreeClassifier as DT
from sklearn import metrics

modelDT = DT()
modelDT = modelDT.fit(X_train, y_train)
preds_DT = modelDT.predict(X_test)
print('Accuracy of DecisionTreeClassifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, preds_DT)))
print('Logistic Regression Confusion Matrix \n', metrics.confusion_matrix(y_test, preds_DT))

Accuracy of DecisionTreeClassifier on test set: 0.44
Logistic Regression Confusion Matrix 
 [[ 42  29  42]
 [ 26  24  33]
 [ 46  35 103]]


### Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn import metrics

model_LR = LR(random_state=0)
model_LR = model_LR.fit(X_train, y_train)
pred_LR = model_LR.predict(X_test)

print('Accuracy of Logistic Regression classifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, pred_LR)))
print('Logistic Regression Confusion Matrix \n', metrics.confusion_matrix(y_test, pred_LR))

Accuracy of Logistic Regression classifier on test set: 0.53
Logistic Regression Confusion Matrix 
 [[ 47   5  61]
 [ 18   2  63]
 [ 25   5 154]]


### XGB Classifier

In [15]:
from xgboost import XGBClassifier

model_XGB = XGBClassifier()
model_XGB.fit(X_train, y_train)
pred_XGB = model_XGB.predict(X_test)

print('Accuracy of XGBoost classifier on test set: {:.2f}'.format(metrics.accuracy_score(y_test, pred_XGB)))
print('XGBoost - Confusion Matrix \n', metrics.confusion_matrix(y_test, pred_XGB))

Accuracy of XGBoost classifier on test set: 0.49
XGBoost - Confusion Matrix 
 [[ 39  20  54]
 [ 20  13  50]
 [ 27  23 134]]
